### ISSUE TITLE
linux-arm32v7 and windows-amd64 tags not available for dotnet core 3.0 

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-functions-docker#226]
From [Readme](https://github.com/Azure/azure-functions-docker/blob/master/README.md), there is linux-arm32v7 and windows-amd64 tags for dotnet core 3.0. However the tags `3.0-arm32v7` and `3.0-nanoserver-1809` listed in readme is not available. Can you share the latest dotnet 3.0 tags for linux arm32v7 and windows?

**Comment by rasavant-ms** [comment]
I do not see any 3.0 image tags on docker hub - https://hub.docker.com/_/microsoft-azure-functions-base

**Comment by blackchoey** [comment]
@rasavant-ms I found the tags in this repo's [readme](https://github.com/Azure/azure-functions-docker/blob/master/README.md).

**Comment by blackchoey** [comment]
Does it mean .net core 3.0 images are not general available yet if there's no 3.0 tags in https://hub.docker.com/_/microsoft-azure-functions-base ?

**Comment by avaneerd** [comment]
I think the build for nanoserver images are failing.
This PR should fix that but is not finished yet: #235 

@ahmelsayed what is the status on this PR?

**Comment by mail2hjain** [comment]
> I think the build for nanoserver images are failing.
> This PR should fix that but is not finished yet: #235
> 
> @ahmelsayed what is the status on this PR?

PR seems to be merged. However, I still don't see the "3.0-nanoserver-1809" tag / image on Docker hub.

**Comment by ahmelsayed** [comment]
```
docker pull mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809
```

should be working now.

**Comment by ahmelsayed** [comment]
as well as 

```
docker pull mcr.microsoft.com/azure-functions/dotnet:3.0-arm32v7
```
